name: local save

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: run py
        run: |
          python3 ./test1.py
          
      - name: commit
        run: |
          git config --global user.email "blackantt@gmail.com"
          git config --global user.name "bk111"
          git add .
          git commit -m "update" -a
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
